#!/usr/bin/env python
"""Audit Cytoview B-well firing-rate outliers from Step 1 unit metrics.

This is a Step 1 inspection helper. It reads the current Cytoview unit metrics
CSV generated by ``build_cytoview_dorsal_ventral_step1_summary.py`` and checks:

- whether A/B well row labels agree with ventral/dorsal region calls,
- whether B1/B2 wells contain unusually high-firing KSLabel=good units,
- how dorsal/ventral summaries move when the most suspicious B1/B2 block is
  excluded.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

import numpy as np
import pandas as pd


DEFAULT_JOB_DIR = Path(
    "/nfs/turbo/umms-parent/axion_mea_spiketurnpike_projectfolder/jobs/"
    "step1_nonlfp_th5_v5_ground_truth_latest"
)
DEFAULT_DATE_LABEL = "20260709"
SUSPECT_RECORDING_PATTERN = r"h1_134-0150_h1_dorsal_and_ventral_exp17_2\(001\)"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--job-dir", type=Path, default=DEFAULT_JOB_DIR)
    parser.add_argument("--date-label", default=DEFAULT_DATE_LABEL)
    parser.add_argument("--high-fr-hz", type=float, default=2.0)
    parser.add_argument("--suspect-recording-pattern", default=SUSPECT_RECORDING_PATTERN)
    args = parser.parse_args()

    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    job_dir = args.job_dir.expanduser().resolve()
    unit_path = job_dir / f"cytoview_dorsal_ventral_step1_{args.date_label}_unit_metrics.csv"
    plan_path = job_dir / f"cytoview_platemap_dorsal_ventral_priority_{args.date_label}_batch_plan.csv"
    units = pd.read_csv(unit_path)
    plan = pd.read_csv(plan_path)
    good = units.loc[units["KSLabel"].astype(str).str.lower().eq("good")].copy()
    good["recording_short"] = good["recording"].map(_short_recording)

    label_validation = _validate_labels(plan, units)
    well_summary = _well_summary(good)
    high_units = good.loc[
        good["well"].isin(["B1", "B2"]) & (good["firing_rate_hz"] >= args.high_fr_hz)
    ].sort_values("firing_rate_hz", ascending=False)
    sensitivity = _sensitivity_summary(good, args.suspect_recording_pattern)

    stem = f"cytoview_b1_b2_firing_rate_audit_{args.date_label}"
    label_csv = job_dir / f"{stem}_label_validation.csv"
    well_csv = job_dir / f"{stem}_well_summary.csv"
    high_csv = job_dir / f"{stem}_high_b1_b2_good_units.csv"
    sensitivity_csv = job_dir / f"{stem}_sensitivity.csv"
    figure_png = job_dir / f"{stem}.png"

    label_validation.to_csv(label_csv, index=False)
    well_summary.to_csv(well_csv, index=False)
    high_units.to_csv(high_csv, index=False)
    sensitivity.to_csv(sensitivity_csv, index=False)
    _plot_audit(plt, well_summary, high_units, sensitivity, figure_png)

    print(f"Label validation CSV: {label_csv}")
    print(f"Well summary CSV: {well_csv}")
    print(f"High B1/B2 good-unit CSV: {high_csv}")
    print(f"Sensitivity CSV: {sensitivity_csv}")
    print(f"Figure PNG: {figure_png}")
    print("\nLabel validation:")
    print(label_validation.to_string(index=False))
    print("\nB1/B2 wells sorted by max firing rate:")
    print(
        well_summary.loc[well_summary["well"].isin(["B1", "B2"])]
        .sort_values("max_fr_hz", ascending=False)
        .head(12)
        .to_string(index=False)
    )
    print("\nSensitivity:")
    print(sensitivity.to_string(index=False))


def _validate_labels(plan: pd.DataFrame, units: pd.DataFrame) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    for name, table, allow_overrides in [
        ("explicit_batch_plan_before_overrides", plan, False),
        ("unit_metrics_final_region_after_overrides", units.drop_duplicates(["recording", "well"]), True),
    ]:
        check = table.copy()
        check["expected_region_from_well_row"] = (
            check["well"].astype(str).str.upper().str[0].map({"A": "ventral", "B": "dorsal"}).fillna("unknown")
        )
        mismatches = check.loc[check["region_call"].astype(str).ne(check["expected_region_from_well_row"].astype(str))]
        if allow_overrides and "region_override_applied" in check.columns:
            intentional = mismatches.loc[mismatches["region_override_applied"].astype(bool)]
            unresolved = mismatches.loc[~mismatches["region_override_applied"].astype(bool)]
        else:
            intentional = mismatches.iloc[0:0]
            unresolved = mismatches
        rows.append(
            {
                "source": name,
                "rows_checked": int(len(check)),
                "row_rule_mismatch_count": int(len(mismatches)),
                "intentional_override_count": int(len(intentional)),
                "unresolved_mismatch_count": int(len(unresolved)),
                "mismatch_examples": "; ".join(
                    f"{row.recording}/{row.well}:{row.region_call}!={row.expected_region_from_well_row}"
                    for row in unresolved.head(5).itertuples()
                ),
            }
        )
    return pd.DataFrame(rows)


def _well_summary(good: pd.DataFrame) -> pd.DataFrame:
    return (
        good.groupby(["recording", "recording_short", "plate_id", "raw_variant", "well", "region_call"], dropna=False)
        .agg(
            good_n=("unit_id", "size"),
            median_fr_hz=("firing_rate_hz", "median"),
            mean_fr_hz=("firing_rate_hz", "mean"),
            max_fr_hz=("firing_rate_hz", "max"),
            fs_n=("rs_fs_classification", lambda values: int((values == "FS_like").sum())),
            borderline_n=("rs_fs_classification", lambda values: int((values == "borderline").sum())),
            rs_n=("rs_fs_classification", lambda values: int((values == "RS_like").sum())),
        )
        .reset_index()
        .sort_values(["max_fr_hz", "mean_fr_hz"], ascending=False)
    )


def _sensitivity_summary(good: pd.DataFrame, suspect_recording_pattern: str) -> pd.DataFrame:
    suspect_b1_b2 = good["recording"].str.contains(suspect_recording_pattern, regex=True) & good["well"].isin(["B1", "B2"])
    suspect_recording = good["recording"].str.contains(suspect_recording_pattern, regex=True)
    scenarios = [
        ("current_all_gui_ready_after_region_override", good),
        ("exclude_134-0150_exp17_2_001_B1_B2", good.loc[~suspect_b1_b2]),
        ("exclude_entire_134-0150_exp17_2_001_recording", good.loc[~suspect_recording]),
    ]
    rows: list[dict[str, object]] = []
    for scenario, table in scenarios:
        for region, subset in table.groupby("region_call", dropna=False):
            rows.append(
                {
                    "scenario": scenario,
                    "region_call": region,
                    "good_units": int(len(subset)),
                    "wells": int(subset[["recording", "well"]].drop_duplicates().shape[0]),
                    "median_fr_hz": _round(subset["firing_rate_hz"].median()),
                    "mean_fr_hz": _round(subset["firing_rate_hz"].mean()),
                    "max_fr_hz": _round(subset["firing_rate_hz"].max()),
                    "FS_like_count": int(subset["rs_fs_classification"].eq("FS_like").sum()),
                    "borderline_count": int(subset["rs_fs_classification"].eq("borderline").sum()),
                    "RS_like_count": int(subset["rs_fs_classification"].eq("RS_like").sum()),
                }
            )
    return pd.DataFrame(rows)


def _plot_audit(
    plt,
    well_summary: pd.DataFrame,
    high_units: pd.DataFrame,
    sensitivity: pd.DataFrame,
    output_path: Path,
) -> None:
    fig, axes = plt.subplots(2, 2, figsize=(15.2, 9.6))
    axes = axes.ravel()
    colors = {"B1": "#e76f51", "B2": "#d62828", "B3": "#f4a261", "A1": "#457b9d", "A2": "#2a9d8f", "A3": "#43aa8b"}

    ordered = well_summary.sort_values("max_fr_hz", ascending=False).head(24).copy()
    ordered["label"] = ordered["plate_id"].astype(str) + " " + ordered["raw_variant"].astype(str) + " " + ordered["well"].astype(str)
    y = np.arange(len(ordered))
    axes[0].barh(y, ordered["max_fr_hz"], color=[colors.get(w, "#999999") for w in ordered["well"]])
    axes[0].set_yticks(y, ordered["label"])
    axes[0].invert_yaxis()
    axes[0].set_xlabel("Max KSLabel=good firing rate (Hz)")
    axes[0].set_title("Top wells by max good-unit firing rate")

    b12 = well_summary.loc[well_summary["well"].isin(["B1", "B2"])].copy()
    b12 = b12.sort_values(["plate_id", "raw_variant", "well", "median_fr_hz"])
    x = np.arange(len(b12))
    axes[1].scatter(x, b12["median_fr_hz"], color=[colors.get(w, "#999999") for w in b12["well"]], s=42, label="median")
    axes[1].scatter(x, b12["max_fr_hz"], color="black", s=24, alpha=0.75, label="max")
    axes[1].set_xticks(x, b12["plate_id"].astype(str) + "\n" + b12["raw_variant"].astype(str) + "\n" + b12["well"].astype(str), rotation=90)
    axes[1].set_ylabel("Firing rate (Hz)")
    axes[1].set_title("B1/B2 good-unit firing rates by recording")
    axes[1].legend(frameon=False, fontsize=8)
    axes[1].grid(axis="y", color="0.9")

    for region, subset in high_units.groupby("region_call", dropna=False):
        axes[2].scatter(
            subset["firing_rate_hz"],
            subset["isi_median_ms"],
            s=42,
            alpha=0.75,
            label=str(region),
            color="#d62828",
        )
    axes[2].set_xlabel("B1/B2 high-unit firing rate (Hz)")
    axes[2].set_ylabel("Median ISI (ms)")
    axes[2].set_title("B1/B2 KSLabel=good units >= high-FR threshold")
    axes[2].grid(color="0.9")

    scenarios = list(sensitivity["scenario"].drop_duplicates())
    for region_index, region in enumerate(["dorsal", "ventral"]):
        subset = sensitivity.loc[sensitivity["region_call"].eq(region)].set_index("scenario").reindex(scenarios)
        axes[3].plot(scenarios, subset["mean_fr_hz"], marker="o", label=f"{region} mean")
        axes[3].plot(scenarios, subset["median_fr_hz"], marker="s", linestyle="--", label=f"{region} median")
    axes[3].set_xticks(np.arange(len(scenarios)), scenarios, rotation=25, ha="right")
    axes[3].set_ylabel("Firing rate (Hz)")
    axes[3].set_title("Dorsal/ventral sensitivity to suspect block")
    axes[3].legend(frameon=False, fontsize=8)
    axes[3].grid(axis="y", color="0.9")

    for ax in axes:
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
    fig.suptitle("Cytoview Step 1 B1/B2 firing-rate audit; KSLabel=good only", y=1.01)
    fig.tight_layout()
    fig.savefig(output_path, dpi=220, bbox_inches="tight")
    plt.close(fig)


def _short_recording(recording: str) -> str:
    recording = str(recording)
    recording = recording.replace("step1_nonlfp_th5_20260708_incoming_manny4tbum_20260706_", "")
    recording = recording.replace("_primary_Neural_Broadband_hp_0.1_Hz_IIR_lp_None", "_primary")
    recording = recording.replace("_primary_Neural_Broadband_hp_0.1_Hz_IIR_lp", "_primary")
    return re.sub(r"_dorsal_and_ventral_", "_DV_", recording)


def _round(value: float) -> float:
    return float(np.round(value, 4)) if np.isfinite(value) else np.nan


if __name__ == "__main__":
    main()
