#!/usr/bin/env bash
# Stage AIND capsule repos locally so Slurm tasks do not clone from GitHub.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
PROJECT_CONFIG="${PROJECT_CONFIG:-${REPO_ROOT}/config/greatlakes_project.env}"
source "${PROJECT_CONFIG}"

versions_file="${AIND_PIPELINE_ROOT}/pipeline/capsule_versions.env"
custom_versions_file="${AIND_PIPELINE_ROOT}/pipeline/capsule_versions_custom.env"
stage_root="${AIND_CAPSULE_REPOS_ROOT}"

if [[ ! -f "${versions_file}" ]]; then
  echo "ERROR: missing AIND capsule versions file: ${versions_file}" >&2
  exit 2
fi

mkdir -p "${stage_root}"

# shellcheck source=/dev/null
source "${versions_file}"

capsules=(
  JOB_DISPATCH
  PREPROCESSING
  SPIKESORT_KS4
  SPIKESORT_KS25
  SPIKESORT_SC2
  SPIKESORT_LUPIN
  POSTPROCESSING
  CURATION
  VISUALIZATION
  RESULTS_COLLECTOR
  QUALITY_CONTROL
  QUALITY_CONTROL_COLLECTOR
  NWB_ECEPHYS
  NWB_UNITS
)

repo_name_from_url() {
  local repo_url="$1"
  local name
  name="$(basename "${repo_url}")"
  name="${name%.git}"
  printf '%s\n' "${name}"
}

stage_one() {
  local prefix="$1"
  local repo_var="${prefix}_REPO"
  local commit_var="${prefix}_COMMIT"
  local repo_url="${!repo_var:-}"
  local commit="${!commit_var:-}"

  if [[ -z "${repo_url}" || -z "${commit}" ]]; then
    echo "ERROR: ${repo_var} or ${commit_var} is missing in ${versions_file}" >&2
    exit 2
  fi

  local repo_name dest actual
  repo_name="$(repo_name_from_url "${repo_url}")"
  dest="${stage_root}/${repo_name}"

  if [[ -d "${dest}/.git" ]]; then
    echo "[${prefix}] updating ${dest}" >&2
    git -C "${dest}" remote set-url origin "${repo_url}"
    git -C "${dest}" fetch --tags origin
  else
    echo "[${prefix}] cloning ${repo_url} -> ${dest}" >&2
    git clone "${repo_url}" "${dest}"
  fi

  git -C "${dest}" checkout --quiet "${commit}"
  actual="$(git -C "${dest}" rev-parse HEAD)"
  if [[ "${actual}" != "${commit}" ]]; then
    echo "ERROR: ${prefix} checkout mismatch: wanted ${commit}, got ${actual}" >&2
    exit 2
  fi
  if [[ ! -d "${dest}/code" ]]; then
    echo "ERROR: ${prefix} staged repo is missing expected code/ directory: ${dest}" >&2
    exit 2
  fi

  printf '%s_REPO="file://%s"\n' "${prefix}" "${dest}"
  printf '%s_COMMIT=%s\n' "${prefix}" "${commit}"
}

tmp_file="${custom_versions_file}.tmp"
{
  echo "# Auto-generated by ${REPO_ROOT}/scripts/stage_aind_capsule_repos.sh"
  echo "# Source pins: ${versions_file}"
  echo "# Generated: $(date -Is)"
  echo "# Purpose: avoid runtime GitHub clones inside Great Lakes Slurm/container jobs."
  for prefix in "${capsules[@]}"; do
    stage_one "${prefix}"
  done
  printf 'SPIKEINTERFACE_VERSION=%s\n' "${SPIKEINTERFACE_VERSION}"
  printf 'EXTRA_INSTALLS="%s"\n' "${EXTRA_INSTALLS:-}"
} > "${tmp_file}"
mv "${tmp_file}" "${custom_versions_file}"

echo "Wrote local AIND capsule versions: ${custom_versions_file}"
echo "Staged repos under: ${stage_root}"
